services:
  - type: web
    name: node-badges-web
    repo: https://github.com/smashedr/node-badges
    plan: free
    runtime: image
    image:
      url: ghcr.io/smashedr/node-badges:latest
    dockerCommand: npm start
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: node-badges-redis
          property: connectionString
    healthCheckPath: /app-health-check

  - type: keyvalue
    name: node-badges-redis
    plan: free
    maxmemoryPolicy: volatile-ttl
    ipAllowList: []
