services:
  - type: web
    name: node-badges
    repo: https://github.com/smashedr/node-badges
    plan: starter
    runtime: node
    startCommand: npm start
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: node-badges-redis
          property: connectionString
    healthCheckPath: /app-health-check

  - type: keyvalue
    name: node-badges-redis
    plan: free
    maxmemoryPolicy: volatile-ttl
    ipAllowList: []
