services:
  - type: web
    name: node-badges
    plan: free
    runtime: image
    image:
      url: ghcr.io/smashedr/node-badges:latest
    dockerCommand: npm start
    healthCheckPath: /app-health-check
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: node-badges-redis
          property: connectionString

  - type: keyvalue
    name: node-badges-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: volatile-ttl
