services:
  - type: web
    name: node-badges
    plan: free
    previews:
      generation: automatic
    runtime: docker
    repo: https://github.com/smashedr/node-badges
    autoDeployTrigger: off
    dockerCommand: npm start
    healthCheckPath: /app-health-check
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: node-badges-redis
          property: connectionString

  - type: keyvalue
    name: node-badges-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: volatile-ttl
