name: "Deploy"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types: [completed]

env:
  stack-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}
  stack-file: docker-compose-swarm.yaml
  traefik-host: badges.cssnr.com

jobs:
  deploy:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment:
      name: swarm
      url: https://badges.cssnr.com/

    steps:
      - name: "Debug Variables"
        continue-on-error: true
        run: |
          echo "VERSION: ${{ github.ref_name }}"
          echo "STACK_NAME: ${{ env.stack-name }}"
          echo "TRAEFIK_HOST: ${{ env.traefik-host }}"

      - name: "Portainer Deploy"
        uses: cssnr/portainer-stack-deploy-action@v1
        with:
          url: ${{ secrets.PORTAINER_URL }}
          token: ${{ secrets.PORTAINER_TOKEN }}
          file: ${{ env.stack-file }}
          name: ${{ env.stack-name }}
          username: ${{ vars.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}
          env_json: |
            {
              "VERSION": "${{ github.ref_name }}",
              "STACK_NAME": "${{ env.stack-name }}",
              "TRAEFIK_HOST": "${{ env.traefik-host }}"
            }
