name: "Pull"

on:
  pull_request_target:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull:
    name: "Pull"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write

    steps:
      - name: "Checkout Pull"
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: "NPM Outdated Check"
        continue-on-error: true
        uses: cssnr/npm-outdated-action@master
